#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════╗
# ║  wal-reload.sh — pywal → awesome/kitty/rofi/dunst/starship  ║
# ╚══════════════════════════════════════════════════════════════╝
set -euo pipefail

WAL_CACHE="$HOME/.cache/wal"
AWM_CFG="$HOME/.config/awesome"
ROFI_CFG="$HOME/.config/rofi"
DUNST_CFG="$HOME/.config/dunst"
KITTY_CFG="$HOME/.config/kitty"
STARSHIP_CFG="$HOME/.config/starship.toml"

if [[ ! -f "$WAL_CACHE/colors.sh" ]]; then
    echo "[wal-reload] No pywal cache found at $WAL_CACHE/colors.sh"
    echo "[wal-reload] Run: wal -i /path/to/wallpaper.jpg"
    exit 1
fi

source "$WAL_CACHE/colors.sh"

BG="$background"
FG="$foreground"
C0="$color0"
C1="$color1"
C2="$color2"
C3="$color3"
C4="$color4"
C5="$color5"
C6="$color6"
C7="$color7"
C8="$color8"
C9="$color9"
C10="$color10"
C11="$color11"
C12="$color12"
C13="$color13"
C14="$color14"
C15="$color15"

strip() { echo "${1#\#}"; }

echo "[wal-reload] Palette loaded: BG=$BG FG=$FG ACCENT=$C5"

# ══════════════════════════════════════════════════════════════
# 1. AWESOME WM — write pywal theme lua
# ══════════════════════════════════════════════════════════════
mkdir -p "$AWM_CFG/themes"
cat > "$AWM_CFG/themes/pywal.lua" << LUAEOF
-- themes/pywal.lua  (auto-generated by wal-reload.sh — do not hand-edit)

local theme = {}

theme.font         = "JetBrainsMono Nerd Font 10"
theme.taglist_font = "JetBrainsMono Nerd Font Bold 10"
theme.title_font   = "JetBrainsMono Nerd Font 9"

local c = {
    bg       = "$BG",
    fg       = "$FG",
    color0   = "$C0",
    color1   = "$C1",
    color2   = "$C2",
    color3   = "$C3",
    color4   = "$C4",
    color5   = "$C5",
    color6   = "$C6",
    color7   = "$C7",
    color8   = "$C8",
    color9   = "$C9",
    color10  = "$C10",
    color11  = "$C11",
    color12  = "$C12",
    color13  = "$C13",
    color14  = "$C14",
    color15  = "$C15",
}
theme.palette = c

theme.bg_normal   = c.bg
theme.bg_focus    = c.color8
theme.bg_urgent   = c.color1
theme.bg_minimize = c.color0
theme.bg_systray  = c.bg

theme.fg_normal   = c.fg
theme.fg_focus    = c.color6
theme.fg_urgent   = c.color7
theme.fg_minimize = c.color8

theme.bg_hover    = c.color8 .. "cc"
theme.widget_bg   = "#00000000"
theme.bar_bg      = c.bg .. "ee"

theme.border_width  = 2
theme.border_normal = c.color0
theme.border_focus  = c.color5
theme.border_marked = c.color3

theme.titlebar_bg_normal  = c.color0
theme.titlebar_bg_focus   = c.bg
theme.titlebar_fg_normal  = c.color8
theme.titlebar_fg_focus   = c.fg
theme.titlebar_size       = 28

theme.tb_close_bg    = c.color1
theme.tb_close_hover = c.color9
theme.tb_max_bg      = c.color3
theme.tb_max_hover   = c.color11
theme.tb_min_bg      = c.color2
theme.tb_min_hover   = c.color10

theme.bar_height       = 36
theme.bar_radius       = 18
theme.bar_margin_top   = 8
theme.bar_margin_side  = 12
theme.bar_opacity      = 0.92
theme.bar_border_width = 1
theme.bar_border_color = c.color8
theme.island_radius    = 10

theme.notification_bg           = c.bg
theme.notification_fg           = c.fg
theme.notification_border_color = c.color5
theme.notification_border_width = 1
theme.notification_shape_radius = 10
theme.notification_font         = "JetBrainsMono Nerd Font 10"
theme.notification_icon_size    = 32
theme.notification_margin       = 14

theme.menu_bg_normal    = c.bg
theme.menu_bg_focus     = c.color8
theme.menu_fg_normal    = c.fg
theme.menu_fg_focus     = c.color5
theme.menu_border_width = 1
theme.menu_border_color = c.color8
theme.menu_height       = 24
theme.menu_width        = 200

theme.taglist_bg_focus    = c.color5
theme.taglist_fg_focus    = c.color0
theme.taglist_bg_occupied = c.color8
theme.taglist_fg_occupied = c.fg
theme.taglist_bg_empty    = "#00000000"
theme.taglist_fg_empty    = c.color8

theme.wallpaper = os.getenv("HOME") .. "/.cache/wal/wal"

return theme
LUAEOF
echo "[wal-reload] ✓ awesome theme: $AWM_CFG/themes/pywal.lua"

# ══════════════════════════════════════════════════════════════
# 2. KITTY — pywal colors
# ══════════════════════════════════════════════════════════════
mkdir -p "$KITTY_CFG"
cat > "$KITTY_CFG/pywal-colors.conf" << KITTYEOF
background ${BG}
foreground ${FG}
cursor      ${FG}
selection_background ${C8}
selection_foreground ${BG}
color0  ${C0}
color1  ${C1}
color2  ${C2}
color3  ${C3}
color4  ${C4}
color5  ${C5}
color6  ${C6}
color7  ${C7}
color8  ${C8}
color9  ${C9}
color10 ${C10}
color11 ${C11}
color12 ${C12}
color13 ${C13}
color14 ${C14}
color15 ${C15}
KITTYEOF
if ! grep -q "pywal-colors.conf" "$KITTY_CFG/kitty.conf" 2>/dev/null; then
    echo "" >> "$KITTY_CFG/kitty.conf"
    echo "include pywal-colors.conf" >> "$KITTY_CFG/kitty.conf"
fi
echo "[wal-reload] ✓ kitty colors"

# ══════════════════════════════════════════════════════════════
# 3. ROFI — overwrite shared/colors.rasi so ALL themes pick it up
#    (both default-theme.rasi and theme-2.rasi @import shared/colors.rasi)
# ══════════════════════════════════════════════════════════════
mkdir -p "$ROFI_CFG/shared"

# Write directly into shared/colors.rasi — this is what rofi themes import
cat > "$ROFI_CFG/shared/colors.rasi" << ROFIEOF
/* pywal colors — auto-generated by wal-reload.sh */
* {
    background:     #$(strip $BG)ff;
    background-alt: #$(strip $C0)ff;
    foreground:     #$(strip $FG)ff;
    selected:       #$(strip $C5)ff;
    active:         #$(strip $C2)ff;
    urgent:         #$(strip $C1)ff;
}
ROFIEOF

# Also keep the dedicated pywal file for reference
cp "$ROFI_CFG/shared/colors.rasi" "$ROFI_CFG/shared/pywal-colors.rasi"

echo "[wal-reload] ✓ rofi colors (shared/colors.rasi updated)"

# ══════════════════════════════════════════════════════════════
# 4. DUNST — patch colors
# ══════════════════════════════════════════════════════════════
if [[ -f "$DUNST_CFG/dunstrc" ]]; then
    sed -i \
        -e "s|background = \".*\" # wal_bg|background = \"$BG\" # wal_bg|g" \
        -e "s|foreground = \".*\" # wal_fg|foreground = \"$FG\" # wal_fg|g" \
        -e "s|frame_color = \".*\" # wal_accent|frame_color = \"$C5\" # wal_accent|g" \
        "$DUNST_CFG/dunstrc" 2>/dev/null || true
fi
echo "[wal-reload] ✓ dunst colors"

# ══════════════════════════════════════════════════════════════
# 5. STARSHIP — patch accent colors
# ══════════════════════════════════════════════════════════════
if [[ -f "$STARSHIP_CFG" ]]; then
    python3 - "$STARSHIP_CFG" "$C5" "$C2" "$C4" "$C3" "$FG" << 'PYEOF'
import sys, re, os

cfg_path = sys.argv[1]
accent   = sys.argv[2]
green    = sys.argv[3]
blue     = sys.argv[4]
yellow   = sys.argv[5]
fg       = sys.argv[6]

with open(cfg_path) as f:
    content = f.read()

def h(c): return c.lstrip('#')

replacements = [
    (r'(style\s*=\s*")[^"]*(".*?# wal-accent)', f'\\g<1>bg:#{h(accent)}\\2'),
    (r'(style\s*=\s*")[^"]*(".*?# wal-green)',  f'\\g<1>bg:#{h(green)}\\2'),
    (r'(style\s*=\s*")[^"]*(".*?# wal-blue)',   f'\\g<1>bg:#{h(blue)}\\2'),
    (r'(style\s*=\s*")[^"]*(".*?# wal-yellow)', f'\\g<1>bg:#{h(yellow)}\\2'),
]

for pattern, repl in replacements:
    content = re.sub(pattern, repl, content)

with open(cfg_path, 'w') as f:
    f.write(content)

print("[wal-reload] ✓ starship colors patched")
PYEOF
fi

# ══════════════════════════════════════════════════════════════
# 6. RELOAD LIVE PROCESSES
# ══════════════════════════════════════════════════════════════

if command -v awesome-client &>/dev/null && pgrep awesome &>/dev/null; then
    awesome-client "
        local tm = require('modules.theme_manager')
        tm.apply('pywal')
    " 2>/dev/null && echo "[wal-reload] ✓ awesome live theme reload" \
                  || echo "[wal-reload] ⚠ awesome-client failed (non-fatal)"
fi

if pgrep dunst &>/dev/null; then
    pkill dunst && sleep 0.1 && dunst &
    echo "[wal-reload] ✓ dunst restarted"
fi

if command -v kill &>/dev/null && pgrep kitty &>/dev/null; then
    pkill -USR1 kitty 2>/dev/null || true
    echo "[wal-reload] ✓ kitty reload signal sent"
fi

echo ""
echo "[wal-reload] ════════════════════════════════"
echo "[wal-reload]  All done! BG=$BG ACCENT=$C5  "
echo "[wal-reload] ════════════════════════════════"
