#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════╗
# ║  wal-reload.sh — pywal → awesome/kitty/rofi/dunst/starship  ║
# ║  Run after `wal -i <image>` or hook into wallpaper setter    ║
# ╚══════════════════════════════════════════════════════════════╝
set -euo pipefail

WAL_CACHE="$HOME/.cache/wal"
AWM_CFG="$HOME/.config/awesome"
ROFI_CFG="$HOME/.config/rofi"
DUNST_CFG="$HOME/.config/dunst"
KITTY_CFG="$HOME/.config/kitty"
STARSHIP_CFG="$HOME/.config/starship.toml"

# ── Bail if pywal cache doesn't exist ──────────────────────────
if [[ ! -f "$WAL_CACHE/colors.sh" ]]; then
    echo "[wal-reload] No pywal cache found at $WAL_CACHE/colors.sh"
    echo "[wal-reload] Run: wal -i /path/to/wallpaper.jpg"
    exit 1
fi

# ── Source wal colors ──────────────────────────────────────────
source "$WAL_CACHE/colors.sh"

# colors: $color0 … $color15, $background, $foreground, $cursor
BG="$background"
FG="$foreground"
C0="$color0"   # black / darkest
C1="$color1"   # red-ish / accent1
C2="$color2"   # green-ish
C3="$color3"   # yellow-ish
C4="$color4"   # blue-ish
C5="$color5"   # magenta/purple
C6="$color6"   # cyan
C7="$color7"   # white/light
C8="$color8"   # bright black
C9="$color9"
C10="$color10"
C11="$color11"
C12="$color12"
C13="$color13"
C14="$color14"
C15="$color15"

# ── Strip # for some tools ─────────────────────────────────────
strip() { echo "${1#\#}"; }

echo "[wal-reload] Palette loaded: BG=$BG FG=$FG ACCENT=$C5"

# ══════════════════════════════════════════════════════════════
# 1. AWESOME WM — write pywal theme lua
# ══════════════════════════════════════════════════════════════
mkdir -p "$AWM_CFG/themes"
cat > "$AWM_CFG/themes/pywal.lua" << LUAEOF
-- themes/pywal.lua  (auto-generated by wal-reload.sh — do not hand-edit)
-- Source: \$HOME/.cache/wal/colors.sh

local theme = {}

-- ─── Fonts ────────────────────────────────────────────────────
theme.font         = "JetBrainsMono Nerd Font 10"
theme.taglist_font = "JetBrainsMono Nerd Font Bold 10"
theme.title_font   = "JetBrainsMono Nerd Font 9"

-- ─── Raw pywal palette ─────────────────────────────────────────
local c = {
    bg       = "$BG",
    fg       = "$FG",
    color0   = "$C0",
    color1   = "$C1",
    color2   = "$C2",
    color3   = "$C3",
    color4   = "$C4",
    color5   = "$C5",
    color6   = "$C6",
    color7   = "$C7",
    color8   = "$C8",
    color9   = "$C9",
    color10  = "$C10",
    color11  = "$C11",
    color12  = "$C12",
    color13  = "$C13",
    color14  = "$C14",
    color15  = "$C15",
}
theme.palette = c

-- ─── Core colors ──────────────────────────────────────────────
theme.bg_normal   = c.bg
theme.bg_focus    = c.color8
theme.bg_urgent   = c.color1
theme.bg_minimize = c.color0
theme.bg_systray  = c.bg

theme.fg_normal   = c.fg
theme.fg_focus    = c.color6
theme.fg_urgent   = c.color7
theme.fg_minimize = c.color8

-- ─── Widget / bar ─────────────────────────────────────────────
theme.bg_hover    = c.color8 .. "cc"
theme.widget_bg   = "#00000000"
theme.bar_bg      = c.bg .. "ee"

-- ─── Borders ──────────────────────────────────────────────────
theme.border_width  = 2
theme.border_normal = c.color0
theme.border_focus  = c.color5
theme.border_marked = c.color3

-- ─── Titlebar ─────────────────────────────────────────────────
theme.titlebar_bg_normal  = c.color0
theme.titlebar_bg_focus   = c.bg
theme.titlebar_fg_normal  = c.color8
theme.titlebar_fg_focus   = c.fg
theme.titlebar_size       = 28

-- Traffic-light buttons
theme.tb_close_bg    = c.color1
theme.tb_close_hover = c.color9
theme.tb_max_bg      = c.color3
theme.tb_max_hover   = c.color11
theme.tb_min_bg      = c.color2
theme.tb_min_hover   = c.color10

-- ─── Bar tokens ───────────────────────────────────────────────
theme.bar_height       = 36
theme.bar_radius       = 18
theme.bar_margin_top   = 8
theme.bar_margin_side  = 12
theme.bar_opacity      = 0.92
theme.bar_border_width = 1
theme.bar_border_color = c.color8
theme.island_radius    = 10

-- ─── Notification ─────────────────────────────────────────────
theme.notification_bg           = c.bg
theme.notification_fg           = c.fg
theme.notification_border_color = c.color5
theme.notification_border_width = 1
theme.notification_shape_radius = 10
theme.notification_font         = "JetBrainsMono Nerd Font 10"
theme.notification_icon_size    = 32
theme.notification_margin       = 14

-- ─── Menu ─────────────────────────────────────────────────────
theme.menu_bg_normal    = c.bg
theme.menu_bg_focus     = c.color8
theme.menu_fg_normal    = c.fg
theme.menu_fg_focus     = c.color5
theme.menu_border_width = 1
theme.menu_border_color = c.color8
theme.menu_height       = 24
theme.menu_width        = 200

-- ─── Taglist ──────────────────────────────────────────────────
theme.taglist_bg_focus    = c.color5
theme.taglist_fg_focus    = c.color0
theme.taglist_bg_occupied = c.color8
theme.taglist_fg_occupied = c.fg
theme.taglist_bg_empty    = "#00000000"
theme.taglist_fg_empty    = c.color8

-- ─── Wallpaper ────────────────────────────────────────────────
theme.wallpaper = os.getenv("HOME") .. "/.cache/wal/wal"

return theme
LUAEOF
echo "[wal-reload] ✓ awesome theme: $AWM_CFG/themes/pywal.lua"

# ══════════════════════════════════════════════════════════════
# 2. KITTY — pywal colors
# ══════════════════════════════════════════════════════════════
cat > "$KITTY_CFG/pywal-colors.conf" << KITTYEOF
# pywal colors for kitty (auto-generated)
background ${BG}
foreground ${FG}
cursor      ${FG}
selection_background ${C8}
selection_foreground ${BG}

color0  ${C0}
color1  ${C1}
color2  ${C2}
color3  ${C3}
color4  ${C4}
color5  ${C5}
color6  ${C6}
color7  ${C7}
color8  ${C8}
color9  ${C9}
color10 ${C10}
color11 ${C11}
color12 ${C12}
color13 ${C13}
color14 ${C14}
color15 ${C15}
KITTYEOF
# Ensure kitty.conf includes the generated file
if ! grep -q "pywal-colors.conf" "$KITTY_CFG/kitty.conf" 2>/dev/null; then
    echo "" >> "$KITTY_CFG/kitty.conf"
    echo "# pywal dynamic colors" >> "$KITTY_CFG/kitty.conf"
    echo "include pywal-colors.conf" >> "$KITTY_CFG/kitty.conf"
fi
echo "[wal-reload] ✓ kitty colors"

# ══════════════════════════════════════════════════════════════
# 3. ROFI — pywal colors
# ══════════════════════════════════════════════════════════════
mkdir -p "$ROFI_CFG/shared"
cat > "$ROFI_CFG/shared/pywal-colors.rasi" << ROFIEOF
/* pywal colors for rofi (auto-generated) */
* {
    background:     $(strip $BG)ff;
    background-alt: $(strip $C0)ff;
    foreground:     $(strip $FG)ff;
    selected:       $(strip $C5)ff;
    active:         $(strip $C2)ff;
    urgent:         $(strip $C1)ff;
}
ROFIEOF
echo "[wal-reload] ✓ rofi colors"

# ══════════════════════════════════════════════════════════════
# 4. DUNST — regenerate dunstrc with pywal colors
# ══════════════════════════════════════════════════════════════
# Only touch the color values, preserve the rest of dunstrc
if [[ -f "$DUNST_CFG/dunstrc" ]]; then
    # Use sed to patch color lines inline
    sed -i \
        -e "s|background = \".*\" # wal_bg|background = \"$BG\" # wal_bg|g" \
        -e "s|foreground = \".*\" # wal_fg|foreground = \"$FG\" # wal_fg|g" \
        -e "s|frame_color = \".*\" # wal_accent|frame_color = \"$C5\" # wal_accent|g" \
        "$DUNST_CFG/dunstrc" 2>/dev/null || true
    
    # If markers not present, write a fresh minimal dunstrc
    if ! grep -q "wal_bg" "$DUNST_CFG/dunstrc"; then
        cat > "$DUNST_CFG/dunstrc.wal" << DUNSTEOF
# dunstrc — pywal section (source this or merge into dunstrc)
[pywal_urgency_low]
    background = "$BG" # wal_bg
    foreground = "$FG" # wal_fg
    frame_color = "$C4" # wal_accent
    timeout = 5

[pywal_urgency_normal]
    background = "$BG" # wal_bg
    foreground = "$FG" # wal_fg
    frame_color = "$C5" # wal_accent
    timeout = 5

[pywal_urgency_critical]
    background = "$BG" # wal_bg
    foreground = "$C1" # wal_fg
    frame_color = "$C1" # wal_accent
    timeout = 0
DUNSTEOF
        echo "[wal-reload] ✓ dunst pywal snippet: $DUNST_CFG/dunstrc.wal"
    fi
fi
echo "[wal-reload] ✓ dunst colors"

# ══════════════════════════════════════════════════════════════
# 5. STARSHIP — update accent colors
# ══════════════════════════════════════════════════════════════
# Starship doesn't support external color files, so we patch the TOML
# We use marker comments to find our generated sections
if [[ -f "$STARSHIP_CFG" ]]; then
    python3 - "$STARSHIP_CFG" "$C5" "$C2" "$C4" "$C3" "$FG" << 'PYEOF'
import sys, re, os

cfg_path = sys.argv[1]
accent   = sys.argv[2]  # color5 → directory/git
green    = sys.argv[3]  # color2 → git ok
blue     = sys.argv[4]  # color4 → lang blocks
yellow   = sys.argv[5]  # color3 → time block
fg       = sys.argv[6]  # foreground

with open(cfg_path) as f:
    content = f.read()

# Strip '#' for TOML color strings that Starship accepts as hex
def h(c): return c.lstrip('#')

replacements = [
    (r'(style\s*=\s*")[^"]*(".*?# wal-accent)', f'\\g<1>bg:#{h(accent)}\\2'),
    (r'(style\s*=\s*")[^"]*(".*?# wal-green)',  f'\\g<1>bg:#{h(green)}\\2'),
    (r'(style\s*=\s*")[^"]*(".*?# wal-blue)',   f'\\g<1>bg:#{h(blue)}\\2'),
    (r'(style\s*=\s*")[^"]*(".*?# wal-yellow)', f'\\g<1>bg:#{h(yellow)}\\2'),
]

for pattern, repl in replacements:
    content = re.sub(pattern, repl, content)

with open(cfg_path, 'w') as f:
    f.write(content)

print("[wal-reload] ✓ starship colors patched (wal markers found)")
PYEOF
fi

# ══════════════════════════════════════════════════════════════
# 6. RELOAD LIVE PROCESSES
# ══════════════════════════════════════════════════════════════

# Tell awesome to switch to pywal theme
if command -v awesome-client &>/dev/null && pgrep awesome &>/dev/null; then
    awesome-client "
        local tm = require('modules.theme_manager')
        tm.apply('pywal')
    " 2>/dev/null && echo "[wal-reload] ✓ awesome live theme reload" \
                  || echo "[wal-reload] ⚠ awesome-client failed (non-fatal)"
fi

# Restart dunst to pick up new colors
if pgrep dunst &>/dev/null; then
    pkill dunst && sleep 0.1 && dunst &
    echo "[wal-reload] ✓ dunst restarted"
fi

# kitty live reload (if running)
if command -v kill &>/dev/null && pgrep kitty &>/dev/null; then
    pkill -USR1 kitty 2>/dev/null || true
    echo "[wal-reload] ✓ kitty reload signal sent"
fi

echo ""
echo "[wal-reload] ════════════════════════════════"
echo "[wal-reload]  All done! Palette from pywal   "
echo "[wal-reload]  BG=$BG  ACCENT=$C5            "
echo "[wal-reload] ════════════════════════════════"
